SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
CREATE SCHEMA `biblioteka`;
USE `biblioteka`;

CREATE TABLE `user` (
	`id_user` INT PRIMARY KEY AUTO_INCREMENT,
    `firstname` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `lastname` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `username` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL UNIQUE,
    `password` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `user_type` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL DEFAULT 'admin'
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `book` (
	`id_book` INT PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `author` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `release_date` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `quantity` INT DEFAULT 0
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `borrowed_books` (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`firstname` VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `lastname` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `date_take` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `date_return` VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_CROATIAN_CI NOT NULL,
    `id_book` INT NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `borrowed_books`
	ADD CONSTRAINT `fk_book_is_borrowed_to` FOREIGN KEY (`id_book`)
    REFERENCES `book` (`id_book`) ON DELETE CASCADE ON UPDATE CASCADE;
